<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DepartamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 1]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 1]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 1]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 2]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 2]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 2]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 3]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 3]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 3]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Petrolina - PE', 'unidade_id' => 4]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Petrolina - PE', 'unidade_id' => 4]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Petrolina - PE', 'unidade_id' => 4]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Petrolina - PE', 'unidade_id' => 5]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Petrolina - PE', 'unidade_id' => 5]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Petrolina - PE', 'unidade_id' => 5]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Vitória de Santo Antão - PE', 'unidade_id' => 6]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Vitória de Santo Antão - PE', 'unidade_id' => 6]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Vitória de Santo Antão - PE', 'unidade_id' => 6]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Vitória de Santo Antão - PE', 'unidade_id' => 7]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Vitória de Santo Antão - PE', 'unidade_id' => 7]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Vitória de Santo Antão - PE', 'unidade_id' => 7]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Caruaru - PE', 'unidade_id' => 8]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Caruaru - PE', 'unidade_id' => 8]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Caruaru - PE', 'unidade_id' => 8]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Caruaru - PE', 'unidade_id' => 9]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Caruaru - PE', 'unidade_id' => 9]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Caruaru - PE', 'unidade_id' => 9]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Barreiros - PE', 'unidade_id' => 10]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Barreiros - PE', 'unidade_id' => 10]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Barreiros - PE', 'unidade_id' => 10]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Belo Jardim - PE', 'unidade_id' => 11]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Belo Jardim - PE', 'unidade_id' => 11]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Belo Jardim - PE', 'unidade_id' => 11]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Belo Jardim - PE', 'unidade_id' => 12]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Belo Jardim - PE', 'unidade_id' => 12]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Belo Jardim - PE', 'unidade_id' => 12]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Garanhuns - PE', 'unidade_id' => 13]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Garanhuns - PE', 'unidade_id' => 13]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Garanhuns - PE', 'unidade_id' => 13]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Garanhuns - PE', 'unidade_id' => 14]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Garanhuns - PE', 'unidade_id' => 14]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Garanhuns - PE', 'unidade_id' => 14]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Serra Talhada - PE', 'unidade_id' => 15]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Serra Talhada - PE', 'unidade_id' => 15]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Serra Talhada - PE', 'unidade_id' => 15]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Serra Talhada - PE', 'unidade_id' => 16]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Serra Talhada - PE', 'unidade_id' => 16]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Serra Talhada - PE', 'unidade_id' => 16]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Cabo Santo Agostinho - PE', 'unidade_id' => 17]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Cabo Santo Agostinho - PE', 'unidade_id' => 17]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Cabo Santo Agostinho - PE', 'unidade_id' => 17]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Cabo Santo Agostinho - PE', 'unidade_id' => 18]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Cabo Santo Agostinho - PE', 'unidade_id' => 18]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 18]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 19]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 19]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 19]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 20]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 20]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 20]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 21]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 21]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 21]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 22]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 22]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 22]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 23]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 23]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 23]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Recife - PE', 'unidade_id' => 24]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Recife - PE', 'unidade_id' => 24]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Recife - PE', 'unidade_id' => 24]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Camaragibe - PE', 'unidade_id' => 25]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Camaragibe - PE', 'unidade_id' => 25]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Camaragibe - PE', 'unidade_id' => 25]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Garanhuns - PE', 'unidade_id' => 26]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Garanhuns - PE', 'unidade_id' => 26]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Garanhuns - PE', 'unidade_id' => 26]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Narazé da Mata - PE', 'unidade_id' => 27]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Narazé da Mata - PE', 'unidade_id' => 27]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Narazé da Mata - PE', 'unidade_id' => 27]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Caruaru - PE', 'unidade_id' => 28]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Caruaru - PE', 'unidade_id' => 28]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Caruaru - PE', 'unidade_id' => 28]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Serra Talhada - PE', 'unidade_id' => 29]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Serra Talhada - PE', 'unidade_id' => 29]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Serra Talhada - PE', 'unidade_id' => 29]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Araripina - PE', 'unidade_id' => 30]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Araripina - PE', 'unidade_id' => 30]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Araripina - PE', 'unidade_id' => 30]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Araripina - PE', 'unidade_id' => 31]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Araripina - PE', 'unidade_id' => 31]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Araripina - PE', 'unidade_id' => 31]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Araripina - PE', 'unidade_id' => 32]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Araripina - PE', 'unidade_id' => 32]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Araripina - PE', 'unidade_id' => 32]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Araripina - PE', 'unidade_id' => 33]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Araripina - PE', 'unidade_id' => 33]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Araripina - PE', 'unidade_id' => 33]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Arcoverde - PE', 'unidade_id' => 34]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Arcoverde - PE', 'unidade_id' => 34]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Arcoverde - PE', 'unidade_id' => 34]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Afogados da Ingazeira - PE', 'unidade_id' => 35]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Afogados da Ingazeira - PE', 'unidade_id' => 35]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Afogados da Ingazeira - PE', 'unidade_id' => 35]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Afogados da Ingazeira - PE', 'unidade_id' => 36]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Afogados da Ingazeira - PE', 'unidade_id' => 36]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Afogados da Ingazeira - PE', 'unidade_id' => 36]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Garanhuns - PE', 'unidade_id' => 37]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Garanhuns - PE', 'unidade_id' => 37]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Garanhuns - PE', 'unidade_id' => 37]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Garanhuns - PE', 'unidade_id' => 38]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Garanhuns - PE', 'unidade_id' => 38]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Garanhuns - PE', 'unidade_id' => 38]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Goiana - PE', 'unidade_id' => 39]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Goiana - PE', 'unidade_id' => 39]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Goiana - PE', 'unidade_id' => 39]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Goiana - PE', 'unidade_id' => 40]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Goiana - PE', 'unidade_id' => 40]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Goiana - PE', 'unidade_id' => 40]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Palmares - PE', 'unidade_id' => 41]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Palmares - PE', 'unidade_id' => 41]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Palmares - PE', 'unidade_id' => 41]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Palmares - PE', 'unidade_id' => 42]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Palmares - PE', 'unidade_id' => 42]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Palmares - PE', 'unidade_id' => 42]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Serra Talhada - PE', 'unidade_id' => 43]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Serra Talhada - PE', 'unidade_id' => 43]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Serra Talhada - PE', 'unidade_id' => 43]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Serra Talhada - PE', 'unidade_id' => 44]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Serra Talhada - PE', 'unidade_id' => 44]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Serra Talhada - PE', 'unidade_id' => 44]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Belém de São Francisco - PE', 'unidade_id' => 45]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Belém de São Francisco - PE', 'unidade_id' => 45]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Belém de São Francisco - PE', 'unidade_id' => 45]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Belo Jardim - PE', 'unidade_id' => 46]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Belo Jardim - PE', 'unidade_id' => 46]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Belo Jardim - PE', 'unidade_id' => 46]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Belo Jardim - PE', 'unidade_id' => 47]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Belo Jardim - PE', 'unidade_id' => 47]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Belo Jardim - PE', 'unidade_id' => 47]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Limoeiro - PE', 'unidade_id' => 48]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Limoeiro - PE', 'unidade_id' => 48]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Limoeiro - PE', 'unidade_id' => 48]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Petrolina - PE', 'unidade_id' => 49]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Petrolina - PE', 'unidade_id' => 49]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Petrolina - PE', 'unidade_id' => 49]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | Salgueiro - PE', 'unidade_id' => 50]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | Salgueiro - PE', 'unidade_id' => 50]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | Salgueiro - PE', 'unidade_id' => 50]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | PE', 'unidade_id' => 51]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | PE', 'unidade_id' => 51]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | PE', 'unidade_id' => 51]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | PE', 'unidade_id' => 52]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | PE', 'unidade_id' => 52]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | PE', 'unidade_id' => 52]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | PE', 'unidade_id' => 53]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | PE', 'unidade_id' => 53]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | PE', 'unidade_id' => 53]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Pedagógico | PE', 'unidade_id' => 54]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Acadêmico | PE', 'unidade_id' => 54]);
        \App\Models\Departamento::factory(1)->create(['nome' => 'Administrativo | PE', 'unidade_id' => 54]);

    }
}
