@extends('layouts.formulario')

@section('content')
    @if($solicitacao->estado_pagina == 0)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 1)
        @include('solicitacao.responsavel')
    @elseif($solicitacao->estado_pagina == 2)
        @include('solicitacao.')
    @elseif($solicitacao->estado_pagina == 3)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 4)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 5)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 6)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 7)
        @include('solicitacao.solicitacao')
    @elseif($solicitacao->estado_pagina == 8)
        @include('solicitacao.solicitacao')
    @endif
@endsection
