<nav class="nav w-100 justify-content-between mb-2">
    <a class="nav-link btn btn-info @if($solicitacao->estado_pagina == 0) active @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 0])}}">1</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 1) btn-info @if($solicitacao->estado_pagina == 1) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 1])}}">2</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 2) btn-info @if($solicitacao->estado_pagina == 2) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 2])}}">3</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 3) btn-info @if($solicitacao->estado_pagina == 3) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 3])}}">4</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 4) btn-info @if($solicitacao->estado_pagina == 4) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 4])}}">5</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 5) btn-info @if($solicitacao->estado_pagina == 5) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 5])}}">6</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 6) btn-info @if($solicitacao->estado_pagina == 6) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 6])}}">7</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 7) btn-info @if($solicitacao->estado_pagina == 7) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 7])}}">8</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 8) btn-info @if($solicitacao->estado_pagina == 8) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 8])}}">9</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 9) btn-info @if($solicitacao->estado_pagina == 9) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 9])}}">10</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 10) btn-info @if($solicitacao->estado_pagina == 10) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 10])}}">11</a>
    <a class="nav-link btn @if($solicitacao->estado_pagina_maximo >= 11) btn-info @if($solicitacao->estado_pagina == 11) active @endif @else btn-secondary disabled @endif cellNav" href="{{route('solicitacao.alterar.pagina', ['solicitacao_id' => $solicitacao->id, 'num_pagina' => 11])}}">12</a>
</nav>
